Panel administacyjny do zarządzania użytkowanikami
pansamochodzik/Cepik pull request #29
Opened 2020-07-14 16:03 UTC by pansamochodzik

2020-07-14 16:06 UTC, pansamochodzik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Panel administacyjny do zarządzania użytkowanikami](https://trello.com/c/WBAw3SOL/28-panel-administacyjny-do-zarz%C4%85dzania-u%C5%BCytkowanikami)

2020-07-28 18:15 UTC, maciejgruszczynski requested changes
Przydałoby się miec seed'a z userami (admin i nie-admin) - chciałbym robiąc setup aplikacji mieć ją gotową do pracy developerskiej. Oczywiście z jakimś lipnym hasłetm typu '12345678'  :)

2020-07-28 18:15 UTC, maciejgruszczynski commented on app/controllers/users_controller.rb
> +    redirect_to root_path, alert: 'Permissions denied' unless
po co to zawinięcie linii?  zrobiłbym wszystko w jednej linii

2020-07-28 18:15 UTC, maciejgruszczynski commented on app/views/users/_form.html.erb
> +        <%= form.select :admin, ['true', 'false'], selected: @user.admin %>
niby ok  @user.admin zwraca true / false. Ale osobiście bym wolał mieć tutaj @user.is_admin? - od razu na pierwszy rzut oka widac (po pytajniku), że będziemy zwracać true/false.

do tego metodka prywatne is_admin? w modelu Use :)

2020-07-28 18:15 UTC, maciejgruszczynski commented on app/controllers/users/confirmations_controller.rb
> +  def after_confirmation_path_for(resource_name, resource)
rozumiem że wiesz, co się dzieje w tej metodzie? ;)

2020-07-29 10:27 UTC, pansamochodzik commented on app/controllers/users/confirmations_controller.rb
> +  def after_confirmation_path_for(resource_name, resource)
Po stworzeniu użytkownika wysyła maila z linkiem do ustawienia hasła bazując na oknie do resetowania hasła.

2020-07-29 10:53 UTC, pansamochodzik commented on app/views/users/_form.html.erb
> +        <%= form.select :admin, ['true', 'false'], selected: @user.admin %>
Nie rozumiem. Jeśli chodzi o 13 linijkę to skąd select miało by wiedzieć czy ma wyświetlać true i false jako wybór?

<p>
    <%= form.label :admin %>
    <%= form.select :admin, ['true', 'false'] %>
</p>

aktualnie wygląda to tak.
selected: @user.admin było zbędne 
tak samo if, bo przecież użytkownika może tworzyć tylko admin

2020-07-29 12:19 UTC, pansamochodzik commented on app/views/users/_form.html.erb
> +        <%= form.select :admin, ['true', 'false'], selected: @user.admin %>
Dobra ten if był potrzebny.

2020-07-30 12:08 UTC, closed without merging